
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxrwjufdiiuxqfmxtnni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4cndqdWZkaWl1eHFmbXh0bm5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjg2MDgsImV4cCI6MjA1ODcwNDYwOH0.6VuZ_Ps-a_AnO-t-P1jpJiDAOUj42Vj6EOeIGoEys-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
