// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pemzepzmuucdvyhdfqqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlbXplcHptdXVjZHZ5aGRmcXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjQ3NzUsImV4cCI6MjA1ODcwMDc3NX0.m822fjFdNAI7VvTpb6LgWHkLOJOEJvMLJXWpYbaYDBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);